name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test5
      id: test5
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test5
        setup-command: ''
        command: "/bin/bash test5.sh"
        input: ''
        expected-output: |-
          Test 1: PASS
          Test 2: PASS
          Test 3: PASS
        comparison-method: exact
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST5_RESULTS: "${{steps.test5.outputs.result}}"
      with:
        runners: test5
